name: gamecatalog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  url_launcher: ^6.3.1
  awesome_snackbar_content: ^0.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/Events/
    - images/Game/
    - images/Game/Dota2_1/
    - images/Game/minecraft_2/
    - images/Game/HSR_3/
    - images/Game/fortnite_4/
    - images/Game/ZZZ_5/
    - images/Game/valorant_6/
    - images/Game/Lol_7/
    - images/Game/pubg_8/
    - images/Game/ml_9/
    - images/Game/genshin_10/
    - images/News/
    - images/Promo/
    - images/Vector/
